name: Java Build

on:
  workflow_dispatch:
    inputs:
      run_clean:
        description: 'Perform a clean build?'
        required: true
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run ShadowJar Task
        run: |
          if [ "${{ github.event.inputs.run_clean }}" = "true" ]; then
            echo "Starting clean shadowJar build..."
            ./gradlew clean shadowJar
          else
            echo "Starting standard shadowJar build..."
            ./gradlew shadowJar
          fi
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Shadow JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: shadow-jar
          path: build/libs/*.jar
          if-no-files-found: info
